import os
import AppKit
import Foundation

private let log = Logger(subsystem: "com.local.multipaste", category: "ClipboardManager")
class ClipboardManager {
    static let shared = ClipboardManager()
    
    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let pasteboard = NSPasteboard.general
    
    // Flag to prevent capturing our own synthetic pastes
    var isPasting = false
    var lastInjectedText: String?
    
    private init() {
        lastChangeCount = pasteboard.changeCount
    }
    
    func startPolling() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        // Ensure timer runs even when UI is interacting
        if let timer = timer {
            RunLoop.current.add(timer, forMode: .common)
        }
    }
    
    func stopPolling() {
        timer?.invalidate()
        timer = nil
    }
    
    private func checkPasteboard() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        let types = pasteboard.types ?? []
        let skipTypes: [NSPasteboard.PasteboardType] = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        ]
        if types.contains(where: { skipTypes.contains($0) }) {
            log.debug("Skipping concealed/transient pasteboard change")
            return
        }
        
        if let frontBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ExclusionManager.shared.isExcluded(frontBundleID) {
            return
        }

        
        log.debug("Pasteboard changed to count: \(currentChangeCount)")
        
        if isPasting {
            // Skip capturing if we are currently injecting a paste
            log.debug("Skipping capture because isPasting is true")
            return
        }
        
        
        if LicenseManager.shared.isProUnlocked,
           let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: NSPasteboard.PasteboardType("public.png")) {
            DatabaseManager.shared.insertImageClip(data: imageData)
            NotificationCenter.default.post(name: NSNotification.Name("NewClipAdded"), object: "Image")
            return
        }
        
        if LicenseManager.shared.isProUnlocked,
           let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !fileURLs.isEmpty {
            let paths = fileURLs.map { $0.path }.joined(separator: "\n")
            DatabaseManager.shared.insertClip(content: paths, type: "file")
            NotificationCenter.default.post(name: NSNotification.Name("NewClipAdded"), object: paths)
            return
        }

        if let text = pasteboard.string(forType: .string) {
            if text == lastInjectedText {
                log.debug("Skipping capture because text matches lastInjectedText: \(text.prefix(20))...")
                return
            }
            
            log.debug("Found text in pasteboard: \(text.prefix(20))... (lastInjectedText was: \(self.lastInjectedText?.prefix(20) ?? "nil"))")
            DatabaseManager.shared.insertClip(content: text, type: "text")
            NotificationCenter.default.post(name: NSNotification.Name("NewClipAdded"), object: text)
        } else {
            log.debug("No string found in pasteboard")
        }
    }
    
    func setPasteboard(content: String) {
        lastInjectedText = content
        pasteboard.clearContents()
        pasteboard.setString(content, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }
}
