import os
import re

# 1. Add os.Logger and replace print in all files
for root, _, files in os.walk('Sources/multipaste'):
    for file in files:
        if file.endswith('.swift'):
            path = os.path.join(root, file)
            with open(path, 'r') as f:
                content = f.read()
            
            if 'import os' not in content:
                content = 'import os\n' + content
            
            classname = file.replace('.swift', '')
            logger_decl = f'private let log = Logger(subsystem: "com.local.multipaste", category: "{classname}")'
            
            if 'private let log =' not in content:
                # insert after imports
                lines = content.split('\n')
                idx = 0
                while idx < len(lines) and (lines[idx].startswith('import ') or lines[idx].strip() == ''):
                    idx += 1
                lines.insert(idx, logger_decl)
                content = '\n'.join(lines)
            
            # replace print( with log.debug(
            content = content.replace('print(', 'log.debug(')
            
            with open(path, 'w') as f:
                f.write(content)

# 2. Update ClipboardManager
with open('Sources/multipaste/ClipboardManager.swift', 'r') as f:
    cm_content = f.read()

injection = """
        let types = pasteboard.types ?? []
        let skipTypes: [NSPasteboard.PasteboardType] = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        ]
        if types.contains(where: { skipTypes.contains($0) }) {
            log.debug("Skipping concealed/transient pasteboard change")
            return
        }
        
        if let frontBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           ExclusionManager.shared.isExcluded(frontBundleID) {
            return
        }
"""
if "org.nspasteboard.ConcealedType" not in cm_content:
    cm_content = cm_content.replace(
        "let currentChangeCount = pasteboard.changeCount\n        guard currentChangeCount != lastChangeCount else { return }\n        lastChangeCount = currentChangeCount",
        "let currentChangeCount = pasteboard.changeCount\n        guard currentChangeCount != lastChangeCount else { return }\n        lastChangeCount = currentChangeCount\n" + injection
    )
with open('Sources/multipaste/ClipboardManager.swift', 'w') as f:
    f.write(cm_content)

# 3. Update DatabaseManager
with open('Sources/multipaste/DatabaseManager.swift', 'r') as f:
    db_content = f.read()

db_injection_prune = """
    func pruneIfNeeded(cap: Int) {
        guard let db = db else { return }
        do {
            let total = try db.scalar(clips.count)
            if total > cap {
                let excess = total - cap
                let oldest = clips.order(timestamp.asc).limit(excess)
                try db.run(oldest.delete())
            }
        } catch {
            log.error("Pruning failed: \\(error)")
        }
    }
    
    func clearAll() {
        guard let db = db else { return }
        try? db.run(clips.delete())
    }
"""

if "func pruneIfNeeded" not in db_content:
    db_content = db_content.replace("func insertClip(content: String, type: String = \"text\") {", db_injection_prune + "\n    func insertClip(content: String, type: String = \"text\") {")
    db_content = db_content.replace("try db?.run(insert)\n        } catch {", "try db?.run(insert)\n            pruneIfNeeded(cap: LicenseManager.shared.isProUnlocked ? Int.max : 50)\n        } catch {")

with open('Sources/multipaste/DatabaseManager.swift', 'w') as f:
    f.write(db_content)

